### ISSUE TITLE
"Cannot read property 'render' of undefined" when trying to render a component

### ISSUE THREAD

**Issue by kibebr** [bitboxer/jsx-no-react#10]
Before explaining the issue I would like to thank you for this module. I am in the process of creating a SPA without React but wanted to use its JSX. I thought I would have to build my own `createElement` replacement but this right here solved all my problems. Thank you.

Say I have a simple component that displays a message:
```js
export const MessageCard = ({ color, content }) => <div class={'card ' + color}>{content}</div>
```

I am trying to append it to the DOM as such:
```js
document.body.appendChild(<MessageCard color='red' content='This is a message.' />)
```

The issue is that when I try to do so, I get this error:
```
module.js:49 Uncaught TypeError: Cannot read property 'render' of undefined
    at createElement (module.js:49)
    at _default (module.js:154)
```

I don't know if I am doing something stupidly wrong or this is a bug. It says the error derives from the method `createElement`:
```js
function createElement(elem, attrs) {
  if (typeof elem.render === "function") {
    return elem.render();
  }
  // ...
}
```
And it seems like `elem` is `null`.

Am I doing something wrong?

Thank you!

**Comment by bitboxer** [comment]
Hm, this is weird. Looks like there is a bug hidden somewhere. I just tried to add your code to another project of mine and it works without problems in it. Can you try to create a repository with it that fails? Would really love to debug this.

**Comment by kibebr** [comment]
@bitboxer 
Hey, thanks for answering.

I am sure I am doing something wrong, but here it is: https://github.com/kibebr/test

**Comment by kibebr** [comment]
Jesus Christ, I am stupid.

The issue is that I was forgetting to destruct  `MessageCard` when importing its module:
```js
import MessageCard from './components/MessageCard.js
```
instead of
```js
import { MessageCard } from './components/MessageCard.js
```

I am sorry @bitboxer!

**Comment by bitboxer** [comment]
No worries, things like these happen to me all the time. Don't take it too hard on yourself.
