### ISSUE TITLE
Rendering document fragments as top-level objects breaks

### ISSUE THREAD

**Issue by JaredSartin** [bitboxer/jsx-no-react#139]
I have frequent need of rendering my children elements into a parent context in web component-lite style. Before we open the can of worms of shadow roots, I am working in a game engine that has a subset of webkit features. I would love to be able to do this:

```
<my-web-component></my-web-component>
```

Rendering with
```
render(<>
  <child-components />
  <child-components />
</>, this)
```

Hoping for an end result of:
```
<my-web-component>
  <child-components />
  <child-components />
</my-web-component>
```

Unfortunately it errors with `Uncaught  TypeError: Arguments[1] expect type : Element` - since DocumentFragments are not an element, but a collection. Unlike appendChild, insertAdjacentElement expects a single element as the second argument.

Possible solutions would be to have render(), renderAppend(), renderPrepend() options replace target content, append to target, and prepend to target (respectively) allowing document fragments. These would use append/prepend, with optional `target.innerHTML ='';` and give most functionality. The advanced renderBefore(), renderAfter() would expect a top-level element - no fragments.

This would would fit the general spirit of JSX a bit better.

**Comment by bitboxer** [comment]
Hm, yes. You are right. Do you want to change the code and open a PR for this?
