### ISSUE TITLE
Remove props tags and values inthe rendered code

### ISSUE THREAD

**Issue by montorodiaz** [bitboxer/jsx-no-react#7]
Hello:

thanks for your work.

This example:

```javascript
function Hello(props) {
  return <h1>Hello {props.name}</h1>;
}

const CustomSeparator = props => (
  <i>{[...Array(props.dots)].map(idx => ".")}</i>
);

function App() {
  return (
    <div>
      <Hello name="foo" />
      <CustomSeparator dots={50} />
      <Hello name="bar" />
    </div>
  );
}

render(<App />, document.body);

```
render like this:
```javascript
<div><h1 name="foo">Hello foo</h1>
<i dots="50">..................................................</i>
<h1 name="bar">Hello bar</h1>
</div>
```
you can see in the rendered code props values and tags:

name="foo"
dots="50"
name="bar"

Is posible, in the rendered code, remove the props values and tags?

In react don't show the props in the rendered code:

[https://codepen.io/pen?&editable=true&editors=0010](https://codepen.io/pen?&editable=true&editors=0010)

I have a code that render like:

```javascript

var arrayUrl = {..}

<Example data={arrayUrl} />

<div data="0: [object Object]; 1: [object Object]; 2: [object Object]; 3: [object Object]; 4: [object Object]; 5: [object Object]">
```

showing all the object that pass in the props.

thanks.

**Comment by bitboxer** [comment]
Oh, yes. We could change the code in that way. Do you want to send a PR with the necessary changes? I would help you and point to the right files and lead you along the way if you want.

**Comment by f107** [comment]
Hello, is it still open in 0.4.1? @bitboxer

**Comment by bitboxer** [comment]
Yes, this is still open and I am happy if you could provide a PR for this.

**Comment by f107** [comment]
I have this issue with 0.3.0, in 0.4.1 works fine, can you check please?

**Comment by bitboxer** [comment]
Haha, you are right. Somehow this is already fixed. Added a test to make sure it stays this way. Thanks for your heads up on this.
